apiVersion: apps/v1
kind: Deployment
metadata:
  name: muzahid-app-frontend-deployment
  labels:
    app: frontend-app
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: {{ .Values.frontend.image }}
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
