apiVersion: v1
kind: Service
metadata:
  name: muzahid-app-backend-service
spec:
  selector:
    app: backend-app
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
